### PR TITLE
hw1 Кравченко Юрий

### PR DESCRIPTION
**Pull request by XJIE6**

### CODE REVIEW

**Comment by eugenyk** [comment]
+ перенесите, пожалуйста в директорию 302_17

**Comment by XJIE6** [comment]
Проблема была в том, что interruptor пытался убить уже заджойненный поток. Пофиксил.

**Comment by eugenyk** [comment]
Неа, снова падает сразу:

Program terminated with signal SIGSEGV, Segmentation fault.
#0  pthread_cancel (th=1) at pthread_cancel.c:33
33        if (INVALID_TD_P (pd))
[Current thread is 1 (Thread 0x7f99258db700 (LWP 11713))]
(gdb) info threads
  Id   Target Id         Frame 
  4    Thread 0x7f99268dd700 (LWP 11711) pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  3    Thread 0x7f99260dc700 (LWP 11712) pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  2    Thread 0x7f992793f740 (LWP 11710) 0x00007f9926ca76bd in pthread_join (threadid=140295736768256, thread_return=0x0) at pthread_join.c:90
* 1    Thread 0x7f99258db700 (LWP 11713) pthread_cancel (th=1) at pthread_cancel.c:33
(gdb) bt
#0  pthread_cancel (th=1) at pthread_cancel.c:33
#1  0x0000000000400ee9 in consumer_interruptor_routine(void*) ()
#2  0x00007f9926ca661a in start_thread (arg=0x7f99258db700) at pthread_create.c:334
#3  0x00007f99269e05fd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) thread 2
[Switching to thread 2 (Thread 0x7f992793f740 (LWP 11710))]
#0  0x00007f9926ca76bd in pthread_join (threadid=140295736768256, thread_return=0x0) at pthread_join.c:90
90          lll_wait_tid (pd->tid);
(gdb) bt
#0  0x00007f9926ca76bd in pthread_join (threadid=140295736768256, thread_return=0x0) at pthread_join.c:90
#1  0x0000000000400f96 in run_threads() ()
#2  0x0000000000400fd6 in main ()
(gdb) thread 3
[Switching to thread 3 (Thread 0x7f99260dc700 (LWP 11712))]
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
185     62:     movl    (%rsp), %edi
(gdb) bt
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x0000000000400e21 in consumer_routine(void*) ()
#2  0x00007f9926ca661a in start_thread (arg=0x7f99260dc700) at pthread_create.c:334
#3  0x00007f99269e05fd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) thread 4
[Switching to thread 4 (Thread 0x7f99268dd700 (LWP 11711))]
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
185     62:     movl    (%rsp), %edi
(gdb) bt
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x0000000000400d7e in producer_routine(void*) ()
#2  0x00007f9926ca661a in start_thread (arg=0x7f99268dd700) at pthread_create.c:334
#3  0x00007f99269e05fd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb)

**Comment by XJIE6** [comment]
Забавно, что у меня ноут не выдавал никаких ошибок. Теперь должно работать

**Pull request merged**
