### PR TITLE
Lab2_3303_Тан Голян

### PR DESCRIPTION
**Pull request by TommyTang930**

### CODE REVIEW

**Comment by TommyTang930** [comment]
changed the interface

**Comment by TommyTang930** [comment]
oh, so sorry, I made a mistake. I will add it again.

**Comment by eugenyk** [comment]
> oh, so sorry, I made a mistake. I will add it again.

When?

**Comment by TommyTang930** [comment]
Today，I will fix it. By the way, Happy Chinese New Year :))) We are on new
year holiday.

Evgeny Kalishenko <notifications@github.com> 于2019年2月6日周三 上午12:44写道：

**Comment by TommyTang930** [comment]
Problem was fixed, please have a check.

我眼中的俄罗斯 <tangtommy930@gmail.com> 于2019年2月6日周三 上午9:39写道：

**Comment by eugenyk** [comment]
Ok, thanks. So we are waiting for the first lab working because this pull request contains that too

**Pull request merged**
