### PR TITLE
Тан Голян__3303 Lab1

### PR DESCRIPTION
**Pull request by TommyTang930**

### CODE REVIEW

**Comment by TommyTang930** [comment]
solved it

**Comment by TommyTang930** [comment]
On my computer all works correctly in this situation. I do not know how to reproduce and fix the problem.

**Comment by eugenyk** [comment]
> On my computer all works correctly in this situation. I do not know how to reproduce and fix the problem.

Send me e-mail and I'll answer with account details for computer where you can reproduce it

**Comment by TommyTang186** [comment]
tangtommy930@gmail.com

**Pull request merged**
